# KSF v4.x "Resonance Separation Model" Configuration
# This file centralizes all parameters for the KSF application,
# focusing on the pre-trained, retrieval-based architecture.

# --- Global Settings ---
force_rebuild_index: false

# --- K-Module: KnowledgeDiscoverer Configuration ---
discoverer:
  model_name: "./snowflake-arctic-embed-m" # The embedding model used for all vectorization.
  adapter_path: "checkpoints/k_module_adapter" # Path to the trained LoRA/PEFT adapter.
  index_dir: "checkpoints/k_module_index_v3_yunhe_adapted_extended" # Directory for the FAISS index and its metadata.
  knowledge_file: "data/云和文旅知识库数据集.json" # Path to the processed knowledge base file.
  weights_file: "data/knowledge_weights.json" # Path to the pre-calculated PageRank weights.
  relevance_threshold: 0.15 # Initial similarity threshold to filter out irrelevant candidates.

  # -- Resonance Separation Model Parameters --
  resonance_alpha: 0.5   # Weight for Sq (query-context similarity).
  resonance_beta: 0.3    # Weight for Ss (structural significance / PageRank).
  resonance_gamma: 0.2   # Weight for Sc (source confidence / from KB or not).
  final_score_threshold: 0.35 # The minimum final score for an item to be included in the ResonancePacket.

# --- S-Module: PromptAssembler Configuration ---
assembler:
  templates_dir: "ksf/s_module/templates" # Directory containing the Jinja2 templates for rendering output.
  manifest_path: "data/knowledge_manifest.json" # Path to the knowledge manifest for intent analysis. 